# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='add_code1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='add_code2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='add_code3',
        ),
        migrations.RemoveField(
            model_name='address',
            name='add_code4',
        ),
        migrations.RemoveField(
            model_name='address',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
